name: gendiff
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install
        # Install package
        run: make install
     # - name: Run linter
        # Run linter
       # run: make lint
      - name: Run test & publish code coverage
        uses: paambaati/codeclimate-action@v5
        # Add Code Climate secret key
        env:
        #  CC_TEST_REPORTER_ID: ${{ secrets.7fcfc1a9e41d7b37ec5adab33242818ebcf6c222a0430407a6174903fd701835 }}
         CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
          coverageLocations: build/logs/clover.xml:clover
          debug: true
